---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.11.0"
    name: clickhouse
  - src: git@github.com:AntonKonyakhin/netology-vector-role.git
    scm: git
    version: "1.0.0"
  - src: git@github.com:AntonKonyakhin/netology-role-lighthouse.git
    scm: git
    version: "1.0.0"
