---
  - name: install clickhose vector
    hosts: clickhouse
    handlers:
      - name: nginx-start
        become: true
        command: service nginx start

    pre_tasks:
      - name: install git
        become: true
        ansible.builtin.apt:
          name: git
          state: present
      - name: install nginx
        become: true
        ansible.builtin.apt:
          name: nginx
          state: present
        notify: nginx-start
    roles: 
      - clickhouse
      - vector-role
      - lighthouse       
